name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up MinGW 32 bit
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x86
          version: 12.2.0

      - name: Run make
        run: make

      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: classic64-windows
          path: dist

  build-linux:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies libsdl2-dev
        run: sudo apt-get install -y libsdl2-dev

      - name: Run make
        run: make
      
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: classic64-linux
          path: dist
